[project]
name = "pydantic-logfire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.2.0",
    "openai==1.99.1",
    "pydantic-ai-slim[openai]>=0.6.2",
]
