[project]
name = "generate-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "logfire>=4.3.3",
    "pydantic-ai-slim[google]>=0.7.0",
    "rich>=14.1.0",
]
