[project]
name = "temporal-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.3.3",
    "pydantic-ai[logfire]>=0.7.4",
    "temporalio>=1.15.0",
]
